### ISSUE TITLE
Party Register API NullpointerException

### ISSUE THREAD

**Issue by sujjangOvO** [sujjangOvO/mk_springboot#13]
accountRepository in PartyDto  NullpointerException

![image](https://user-images.githubusercontent.com/89267864/202972656-c91ed6c9-b6cc-402f-ae88-abaa93a5a1ac.png)

ava.lang.NullPointerException: null
	at com.example.moonkey.dto.PartyDto.getAccounts(PartyDto.java:41) ~[classes/:na]
	at com.example.moonkey.service.PartyService.register(PartyService.java:40) ~[classes/:na]
![image](https://user-images.githubusercontent.com/89267864/202972784-714603bb-1113-4897-b244-cf639e7c2611.png)

**Comment by sujjangOvO** [comment]
사용자 uid를 받아와 특정 store에 party를 register할 때 member를 추가하지 않고 자기 자신만 추가되도록 변경
